nginx:
  container_name: nginx
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    - DEFAULT_HOST=api.dev
  links:
    - api
    - web

api:
  container_name: api
  build: ./api
  ports:
    - "3000:3000"
  expose:
    - 3000
  volumes:
    - ./api:/api
  environment:
    - MYSQL_DATABASE=mydb
    - MYSQL_HOST=mysql
    - MYSQL_PASSWORD=password
    - MYSQL_USER=root
    - PORT=3000
    - VIRTUAL_HOST=api.dev
  links:
    - mysql

web:
  container_name: web
  build: ./web
  ports:
    - "3001:3001"
  expose:
    - 3001
  volumes:
    - ./web:/web
  environment:
    - PORT=3001
    - VIRTUAL_HOST=web.dev

mysql:
  container_name: mysql
  image: mysql:5.7.12
  expose:
    - 3306
  ports:
    - "3306:3306"
  environment:
    MYSQL_DATABASE: mydb
    MYSQL_ROOT_PASSWORD: password

migrations:
  container_name: migrations
  image: mysql:5.7.12
  volumes:
    - ./migrations:/migrations
  command: /migrations/migrate.sh
  links:
    - mysql
