nginx:
  container_name: nginx
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  environment:
    - DEFAULT_HOST=api.local

api:
  container_name: api
  build: ./
  ports:
    - "3000:3000"
  volumes:
    - ./api:/api
  environment:
    - VIRTUAL_HOST=api.local
    - PORT=3000
  links:
    - mysql

mysql:
  container_name: mysql
  image: mysql:5.7.12
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

migrations:
  container_name: migrations
  image: mysql:5.7.12
  volumes:
    - ./migrations:/migrations
  command: sh -c 'mysql -h mysql -u root -ppassword mydb < /migrations/migrations.sql'
  links:
    - mysql
